// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FormTestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void formTesting() {
    // Test name: Form_Testing
    // Step # | name | target | value | comment
    // 1 | open | https://kelanivalleyhospital.lifegroup.lk/jobs/senior-staff-nurses/ |  | 
    driver.get("https://kelanivalleyhospital.lifegroup.lk/jobs/senior-staff-nurses/");
    // 2 | setWindowSize | 697x735 |  | 
    driver.manage().window().setSize(new Dimension(697, 735));
    // 3 | click | id=awsm-applicant-name |  | 
    driver.findElement(By.id("awsm-applicant-name")).click();
    // 4 | type | id=awsm-applicant-name | Gihan Greshan | 
    driver.findElement(By.id("awsm-applicant-name")).sendKeys("Gihan Greshan");
    // 5 | click | id=awsm-applicant-email |  | 
    driver.findElement(By.id("awsm-applicant-email")).click();
    // 6 | type | id=awsm-applicant-email | gihangreshan4@gmail.com | 
    driver.findElement(By.id("awsm-applicant-email")).sendKeys("gihangreshan4@gmail.com");
    // 7 | click | id=awsm-applicant-phone |  | 
    driver.findElement(By.id("awsm-applicant-phone")).click();
    // 8 | type | id=awsm-applicant-phone | 0704960649 | 
    driver.findElement(By.id("awsm-applicant-phone")).sendKeys("0704960649");
    // 9 | click | id=awsm-cover-letter |  | 
    driver.findElement(By.id("awsm-cover-letter")).click();
    // 10 | type | id=awsm-cover-letter | Test | 
    driver.findElement(By.id("awsm-cover-letter")).sendKeys("Test");
    // 11 | click | id=awsm-application-file |  | 
    driver.findElement(By.id("awsm-application-file")).click();
    // 12 | click | id=awsm_form_privacy_policy |  | 
    driver.findElement(By.id("awsm_form_privacy_policy")).click();
    // 13 | verifyChecked | id=awsm_form_privacy_policy |  | 
    assertTrue(driver.findElement(By.id("awsm_form_privacy_policy")).isSelected());
    // 14 | click | id=awsm-application-file |  | 
    driver.findElement(By.id("awsm-application-file")).click();
    // 15 | type | id=awsm-application-file | C:\fakepath\Test CV Submission.pdf | 
    driver.findElement(By.id("awsm-application-file")).sendKeys("C:\\fakepath\\Test CV Submission.pdf");
    // 16 | click | id=awsm-application-submit-btn |  | 
    driver.findElement(By.id("awsm-application-submit-btn")).click();
    // 17 | assertElementPresent | css=.awsm-application-message > p |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".awsm-application-message > p"));
      assert(elements.size() > 0);
    }
  }
}
