// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavigationTestingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigationTesting() {
    // Test name: Navigation_Testing
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://kelanivalleyhospital.lifegroup.lk//");
    // 2 | setWindowSize | 1382x744 |  | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | css=#menu-item-1374 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1374 em")).click();
    // 4 | click | css=#menu-item-1375 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1375 em")).click();
    // 5 | click | css=#menu-item-2422 em |  | 
    driver.findElement(By.cssSelector("#menu-item-2422 em")).click();
    // 6 | click | css=#menu-item-1377 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1377 em")).click();
    // 7 | click | css=#menu-item-2089 em |  | 
    driver.findElement(By.cssSelector("#menu-item-2089 em")).click();
    // 8 | click | css=#menu-item-1376 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1376 em")).click();
  }
}
