// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navigationTesting() {
    // Test name: Navigation_Testing
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://kelanivalleyhospital.lifegroup.lk/jobs/senior-staff-nurses//");
    // 2 | setWindowSize | 1382x744 |  | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | css=#menu-item-1374 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1374 em")).click();
    // 4 | click | css=#menu-item-1375 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1375 em")).click();
    // 5 | click | css=#menu-item-2422 em |  | 
    driver.findElement(By.cssSelector("#menu-item-2422 em")).click();
    // 6 | click | css=#menu-item-1377 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1377 em")).click();
    // 7 | click | css=#menu-item-2089 em |  | 
    driver.findElement(By.cssSelector("#menu-item-2089 em")).click();
    // 8 | click | css=#menu-item-1376 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1376 em")).click();
  }
  @Test
  public void elementsTesting() {
    // Test name: Elements_Testing
    // Step # | name | target | value | comment
    // 1 | open | https://kelanivalleyhospital.lifegroup.lk/contact-us-2/ |  | 
    driver.get("https://kelanivalleyhospital.lifegroup.lk/contact-us-2/");
    // 2 | setWindowSize | 1382x744 |  | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | css=#menu-item-1374 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1374 em")).click();
    // 4 | assertElementPresent | css=.elementor-container:nth-child(3) |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-container:nth-child(3)"));
      assert(elements.size() > 0);
    }
    // 5 | assertElementPresent | css=.elementor-element-391a8f8d .elementor-heading-title |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-element-391a8f8d .elementor-heading-title"));
      assert(elements.size() > 0);
    }
    // 6 | assertElementPresent | css=.elementor-element-6f3b84b .elementor-heading-title |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-element-6f3b84b .elementor-heading-title"));
      assert(elements.size() > 0);
    }
    // 7 | verifyElementPresent | css=b |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("b"));
      assert(elements.size() > 0);
    }
    // 8 | assertTitle | Kelanivalley Hospital |  | 
    assertThat(driver.getTitle(), is("Kelanivalley Hospital"));
    // 9 | assertElementPresent | css=.elementor-element-a0eabe8 strong |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-element-a0eabe8 strong"));
      assert(elements.size() > 0);
    }
    // 10 | click | css=#menu-item-1375 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1375 em")).click();
    // 11 | assertElementPresent | css=.elementor-element-58cf5fb0 .elementor-heading-title |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-element-58cf5fb0 .elementor-heading-title"));
      assert(elements.size() > 0);
    }
    // 12 | assertElementPresent | css=.elementor-icon-list-item:nth-child(2) > .elementor-icon-list-text |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-icon-list-item:nth-child(2) > .elementor-icon-list-text"));
      assert(elements.size() > 0);
    }
    // 13 | assertElementPresent | css=.attachment-medium |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".attachment-medium"));
      assert(elements.size() > 0);
    }
    // 14 | assertElementPresent | css=.text_center > .ekit-heading--title |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".text_center > .ekit-heading--title"));
      assert(elements.size() > 0);
    }
    // 15 | selectFrame | index=0 |  | 
    driver.switchTo().frame(0);
    // 16 | assertElementPresent | css=.\_2zfs |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_2zfs"));
      assert(elements.size() > 0);
    }
    // 17 | selectFrame | relative=parent |  | 
    driver.switchTo().defaultContent();
    // 18 | click | css=#menu-item-1377 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1377 em")).click();
    // 19 | assertElementPresent | css=b |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("b"));
      assert(elements.size() > 0);
    }
    // 20 | assertElementPresent | css=.wp-image-651 |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".wp-image-651"));
      assert(elements.size() > 0);
    }
    // 21 | assertElementPresent | linkText=24-hour Emergency and Outpatient care |  | 
    {
      List<WebElement> elements = driver.findElements(By.linkText("24-hour Emergency and Outpatient care"));
      assert(elements.size() > 0);
    }
    // 22 | assertElementPresent | css=.ekit_heading_mobile- > .ekit-heading--title |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ekit_heading_mobile- > .ekit-heading--title"));
      assert(elements.size() > 0);
    }
    // 23 | assertElementPresent | css=.ekit_heading_mobile- > .ekit-heading--title |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".ekit_heading_mobile- > .ekit-heading--title"));
      assert(elements.size() > 0);
    }
    // 24 | click | css=#menu-item-1376 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1376 em")).click();
    // 25 | click | css=#menu-item-1374 em |  | 
    driver.findElement(By.cssSelector("#menu-item-1374 em")).click();
    // 26 | click | css=#menu-item-2422 em |  | 
    driver.findElement(By.cssSelector("#menu-item-2422 em")).click();
    // 27 | assertElementPresent | css=.awsm-selectric-awsm-job-category-filter-option .awsm-selectric-arrow-drop |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".awsm-selectric-awsm-job-category-filter-option .awsm-selectric-arrow-drop"));
      assert(elements.size() > 0);
    }
    // 28 | click | linkText=More Details |  | 
    driver.findElement(By.linkText("More Details")).click();
    // 29 | assertElementPresent | id=awsm-applicant-name |  | 
    {
      List<WebElement> elements = driver.findElements(By.id("awsm-applicant-name"));
      assert(elements.size() > 0);
    }
    // 30 | assertElementPresent | id=awsm-cover-letter |  | 
    {
      List<WebElement> elements = driver.findElements(By.id("awsm-cover-letter"));
      assert(elements.size() > 0);
    }
    // 31 | assertElementPresent | id=awsm-application-file |  | 
    {
      List<WebElement> elements = driver.findElements(By.id("awsm-application-file"));
      assert(elements.size() > 0);
    }
    // 32 | click | id=awsm_form_privacy_policy |  | 
    driver.findElement(By.id("awsm_form_privacy_policy")).click();
    // 33 | verifyChecked | id=awsm_form_privacy_policy |  | 
    assertTrue(driver.findElement(By.id("awsm_form_privacy_policy")).isSelected());
    // 34 | assertElementPresent | id=awsm-application-submit-btn |  | 
    {
      List<WebElement> elements = driver.findElements(By.id("awsm-application-submit-btn"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void formTesting() {
    // Test name: Form_Testing
    // Step # | name | target | value | comment
    // 1 | open | https://kelanivalleyhospital.lifegroup.lk/jobs/senior-staff-nurses/ |  | 
    driver.get("https://kelanivalleyhospital.lifegroup.lk/jobs/senior-staff-nurses/");
    // 2 | setWindowSize | 697x735 |  | 
    driver.manage().window().setSize(new Dimension(697, 735));
    // 3 | click | id=awsm-applicant-name |  | 
    driver.findElement(By.id("awsm-applicant-name")).click();
    // 4 | type | id=awsm-applicant-name | Gihan Greshan | 
    driver.findElement(By.id("awsm-applicant-name")).sendKeys("Gihan Greshan");
    // 5 | click | id=awsm-applicant-email |  | 
    driver.findElement(By.id("awsm-applicant-email")).click();
    // 6 | type | id=awsm-applicant-email | gihangreshan4@gmail.com | 
    driver.findElement(By.id("awsm-applicant-email")).sendKeys("gihangreshan4@gmail.com");
    // 7 | click | id=awsm-applicant-phone |  | 
    driver.findElement(By.id("awsm-applicant-phone")).click();
    // 8 | type | id=awsm-applicant-phone | 0704960649 | 
    driver.findElement(By.id("awsm-applicant-phone")).sendKeys("0704960649");
    // 9 | click | id=awsm-cover-letter |  | 
    driver.findElement(By.id("awsm-cover-letter")).click();
    // 10 | type | id=awsm-cover-letter | Test | 
    driver.findElement(By.id("awsm-cover-letter")).sendKeys("Test");
    // 11 | click | id=awsm-application-file |  | 
    driver.findElement(By.id("awsm-application-file")).click();
    // 12 | click | id=awsm_form_privacy_policy |  | 
    driver.findElement(By.id("awsm_form_privacy_policy")).click();
    // 13 | verifyChecked | id=awsm_form_privacy_policy |  | 
    assertTrue(driver.findElement(By.id("awsm_form_privacy_policy")).isSelected());
    // 14 | click | id=awsm-application-file |  | 
    driver.findElement(By.id("awsm-application-file")).click();
    // 15 | type | id=awsm-application-file | C:\fakepath\Test CV Submission.pdf | 
    driver.findElement(By.id("awsm-application-file")).sendKeys("C:\\fakepath\\Test CV Submission.pdf");
    // 16 | click | id=awsm-application-submit-btn |  | 
    driver.findElement(By.id("awsm-application-submit-btn")).click();
    // 17 | assertElementPresent | css=.awsm-application-message > p |  | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".awsm-application-message > p"));
      assert(elements.size() > 0);
    }
  }
}
